# Generated by Django 4.2.17 on 2024-12-17 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('can_publish_blog', 'Can publish blog')]},
        ),
    ]
